// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"webook/interactive/events"
	"webook/interactive/grpc"
	"webook/interactive/repository"
	"webook/interactive/repository/cache"
	"webook/interactive/repository/dao"
	"webook/interactive/service"
	"webook/ioc"
)

// Injectors from wire.go:

func InitInteractiveService() service.InteractiveService {
	loggerV1 := InitLogger()
	db := InitDB(loggerV1)
	interactiveDAO := dao.NewInteractiveDAO(db)
	cmdable := InitRedis()
	interactiveCache := cache.NewInteractiveCache(cmdable)
	interactiveRepository := repository.NewInteractiveRepository(interactiveDAO, interactiveCache)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	return interactiveService
}

func InitInteractiveGRPCServer() *grpc.InteractiveServiceServer {
	loggerV1 := InitLogger()
	db := InitDB(loggerV1)
	interactiveDAO := dao.NewInteractiveDAO(db)
	cmdable := InitRedis()
	interactiveCache := cache.NewInteractiveCache(cmdable)
	interactiveRepository := repository.NewInteractiveRepository(interactiveDAO, interactiveCache)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	return interactiveServiceServer
}

// wire.go:

var thirdProvider = wire.NewSet(InitRedis, InitDB, InitLogger, ioc.InitKafkaClient, ioc.InitKafkaProducer)

var interactiveSvcProvider = wire.NewSet(dao.NewInteractiveDAO, cache.NewInteractiveCache, repository.NewInteractiveRepository, service.NewInteractiveService)

// InitConsumers 初始化消费者列表
func InitConsumers(consumer events.Consumer) []events.Consumer {
	return []events.Consumer{consumer}
}
