// Code generated by MockGen. DO NOT EDIT.
// Source: webook/internal/repository/cache/vcode/redis/code.go
//
// Generated by this command:
//
//	mockgen -source=webook/internal/repository/cache/vcode/redis/code.go -package=cachemocks -destination=webook/internal/repository/cache/mocks/code.mock.go
//

// Package cachemocks is a generated GoMock package.
package cachemocks
