// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/interactive/events"
	"webook/interactive/grpc"
	"webook/interactive/ioc"
	"webook/interactive/repository"
	"webook/interactive/repository/cache"
	"webook/interactive/repository/dao"
	"webook/interactive/service"
)

// Injectors from wire.go:

func InitApp() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	interactiveDAO := dao.NewInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewInteractiveCache(cmdable)
	interactiveRepository := repository.NewInteractiveRepository(interactiveDAO, interactiveCache)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.InitGRPCServer(interactiveServiceServer)
	client := ioc.InitKafka()
	kafkaConsumer := events.NewKafkaConsumer(client, loggerV1, interactiveRepository)
	v := ioc.NewConsumers(kafkaConsumer)
	app := &App{
		Server:    server,
		consumers: v,
	}
	return app
}

// wire.go:

var interactiveSvcProvider = wire.NewSet(service.NewInteractiveService, cache.NewInteractiveCache, dao.NewInteractiveDAO, repository.NewInteractiveRepository)

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitRedis, ioc.InitKafka)
